### ISSUE TITLE
use turbo-ws

### ISSUE THREAD

**Issue by soyuka** [soyuka/signalhubws#1]
https://github.com/hugmanrique/turbo-ws

**Comment by corwin-of-amber** [comment]
Seems like that one has been archived. Does that mean it's deprecated?

**Comment by soyuka** [comment]
Mhh yeah you're right, to bad, I was interested by maf's turbo-net library (https://github.com/mafintosh/turbo-net). Anyway, cws that we use here is really performant, let's close this!
