### ISSUE TITLE
Deployent with now

### ISSUE THREAD

**Issue by corwin-of-amber** [soyuka/signalhubws#14]
Can you elaborate on this line in the README?
```
now soyuka/signalhubws
```

I tried to clone the repo and run `now <workdir>`, but did not get a deployed server, just a bunch of static text pages (contents of the js files)...

**Comment by soyuka** [comment]
Just install now and you can deploy a signalhubws server in one command:

```
npm i -g now
cd signalhubws
now
```

Btw it's a websocket server, nothing will be available in http.

**Comment by corwin-of-amber** [comment]
I am sorry, but I did exactly that and I still get just the sources as static pages. (https://signalhubws-9lfc94c5o.now.sh)
I think Now have deprecated the node-server builder and the default builder does not support websockets. I deployed using Heroku instead. It may be useful to update the docs or perhaps a `now.json` can be added to set the builder (I don't know Now well enough).

**Comment by soyuka** [comment]
> I think Now have deprecated the node-server builder and the default builder does not support websockets. 

Oh that's sad... Yeah it might need an update then, thanks for your input.

**Comment by corwin-of-amber** [comment]
I tried this `now.json`, it built successfully but I got 500 Internal Error code from the deployed instance.
```json
{
    "builds": [
        { "src": "*.js", "use": "@now/node-server"}
    ]
}
```

**Comment by soyuka** [comment]
Mhhh but it works to me, I can connect on my deployed hub: `wscat -c wss://signalhubws-zqbbhmeqxg.now.sh`.

I'm going to add a `index.html` so that sources aren't displayed via http.

**Comment by corwin-of-amber** [comment]
My instance returns error code 200... 😭 

Here is my session:
```
% now
> Deploying ~/var/ext/signalhubws under p-wr
> Using project signalhubws
> WARN! Your `package.json` file is missing a `build` property inside the `script` property
> https://signalhubws-mg6yn5m9a.now.sh [v2] [3s]
> Ready! Aliased to https://signalhubws.p-wr.now.sh [in clipboard] [7s]
```
In a browser console:
```
s = new WebSocket('wss://signalhubws-mg6yn5m9a.now.sh')
WebSocket {url: "wss://signalhubws-mg6yn5m9a.now.sh/", readyState: 0, bufferedAmount: 0, onopen: null, onerror: null, …}
VM305:1 WebSocket connection to 'wss://signalhubws-mg6yn5m9a.now.sh/' failed: Error during WebSocket handshake: Unexpected response code: 200
```

**Comment by soyuka** [comment]
Sadly I don't have more time to investigate this :|. Please let me know if you find a solution!

**Comment by corwin-of-amber** [comment]
I found the reason: Zeit have stopped supporting v1 for new accounts. You must have an older account. My account is restricted to v2, which apparently does not support websockets.
<img width="732" alt="Screen Shot 2019-07-16 at 23 16 57" src="https://user-images.githubusercontent.com/704372/61326713-110d1280-a820-11e9-9aad-43d941f7412d.png">

**Comment by soyuka** [comment]
Ah that sucks, let me know if you find an alternative solution. 

Related subjects: https://spectrum.chat/zeit/now/now-v2-looks-amazing-websockets~c2fc8c19-d7be-4882-94de-58ca776c81f4 and https://spectrum.chat/zeit/feature-requests/websocket-support-in-now-v2~fdd32aa5-cac6-449d-8380-c557e0b03511

**Comment by corwin-of-amber** [comment]
As I mentioned, Heorku works great. I've been using it for a while. I can write instructions for deployment if you think visitors to this repo may find it useful.

**Comment by soyuka** [comment]
I definitely can't say no to such contribution :)

**Comment by corwin-of-amber** [comment]
Oh I noticed that @geut already added a Heroku deploy button in [their fork](https://github.com/geut/signalhubws).

I will make a PR with instructions for command-line deployment as well.

**Comment by soyuka** [comment]
Cool, thanks!
