### ISSUE TITLE
Avoid using the window global object

### ISSUE THREAD

**Issue by louisgv** [soyuka/signalhubws#2]
Some application, like [hyperproxy](https://github.com/goonism/hyperproxy) requires a node server to also connect to a signalhubws so that it can serves other browser peer. 

In order for `signalhubws` to be a module consumable by node, it should avoid using the window object and instead accept an argument in the constructor for the client's WebSocket implementation. This would allows the client to switch WebSocket library as needed as per #1 

Specifically this line: https://github.com/soyuka/signalhubws/blob/master/index.js#L28

If the `ws` API are inconsistent, we should notify the `ws` library maintainer to adhere to a standard API.

cc @ColdSauce

**Comment by soyuka** [comment]
Never thought I'd want to use this module's client within nodejs but why not :). 

I've added a comment to the PR let's continue the discussion there.
