### ISSUE TITLE
uws is deprecated

### ISSUE THREAD

**Issue by G-Ray** [soyuka/signalhubws#4]
https://www.npmjs.com/package/uws

**Comment by soyuka** [comment]
Not deprecated he just no longer uses npmjs and that's fine by me, current version works just fine I see no reason to change.

**Comment by G-Ray** [comment]
Well, at least it does not install correctly on my system (fedora 29)
- Node 10
- gcc 8.2.1

```
src/signalhubws/node_modules/uws/uws.js:40
            throw new Error('Compilation of µWebSockets has failed and there is no pre-compiled binary ' +
            ^

Error: Compilation of µWebSockets has failed and there is no pre-compiled binary available for your system. Please install a supported C++11 compiler and reinstall the module 'uws'.
```

Also I'm unable to find the relevant repo in https://github.com/alexhultman repositories.

If you are not against this idea, we may use https://github.com/ClusterWS/uWS instead.

**Comment by G-Ray** [comment]
This is blocking as uws does not compile against Node > 10.
I opened a PR, feel free to comment, accept or reject https://github.com/soyuka/signalhubws/pull/5
